name: Doc

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_docs:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Rust documentation
        run: |
          cd rust
          cargo doc --no-deps
      - name: Publish Rust documentation
        run: |
          cd rust/target/doc
          git init
          git add .
          git -c user.name='tigroo' -c user.email='frederic.gardes@orange.com' commit -m init
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'