name: Schema validation

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List schemas
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$( ./schema/ls )"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  validate:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            --disable-pip-version-check \
            --no-deps \
            --no-warn-script-location \
            attrs==22.1.0 \
            certifi==2022.6.15.2 \
            charset-normalizer==2.1.1 \
            idna==3.4 \
            jsonschema==4.16.0 \
            pyrsistent==0.18.1 \
            requests==2.28.1 \
            urllib3==1.26.12
      - name: Validate one schema
        run: |
          ./schema/validate ${{ matrix.schema }}
